### PR TITLE
Update .dockerignore

### PR DESCRIPTION
**Pull request by Danfocus**
fix wrong exclude

### CODE REVIEW

**Comment by ojab** [comment]
>A leading slash matches the beginning of the pathname. For example, "/*.c" matches "cat-file.c" but not "mozilla-sha1/sha1.c".

so it matches only top-level `dante_config_generator.rb` and it works correctly here (`Docker version 18.04.0-ce, build 3d479c0`).

Is there any issues with current pattern?

**Comment by Danfocus** [comment]
$ docker --version
Docker version 17.05.0-ce, build 89658be
$ docker-compose --version
docker-compose version 1.18.0, build 8dd22a9

Just **docker build .** works fine.

Compose fail with log:
`Step 2/10 : COPY dante_config_generator.rb .
ERROR: Service 'dante' failed to build: lstat dante_config_generator.rb: no such file or directory`

Or fix with **/!dante_config_generator.rb**

**Comment by ojab** [comment]
Understood, could you please change it to `/!dante_config_generator.rb` (I prefer more strict form)
and add something like
 ```
`docker build .` works fine, but `docker`docker-compose up --build` 
(or what exactly you're running) fails with current .dockerignore
```
to the commit message?

**Comment by Danfocus** [comment]
Request updated

**Comment by ojab** [comment]
Merged, thanks.

**Comment by ojab** [comment]
Heh, `/!dante_config_generator.rb` actually breaks `docker-compose version 1.20.1, build 5d8c71b` here, changed to version without leading slash.

**Pull request merged**
